steps:
# Build and push aika-backend image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/aikaapp-584fa/aika-backend', './backend']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/aikaapp-584fa/aika-backend']

# Deploy aika-backend to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: [
    'run', 'deploy', 'aika-backend',
    '--image', 'gcr.io/aikaapp-584fa/aika-backend',
    '--region', 'asia-northeast1',
    '--platform', 'managed',
    '--allow-unauthenticated',
    '--timeout=600s',
    '--update-secrets=GOOGLE_PROJECT_ID=GOOGLE_PROJECT_ID:latest,GOOGLE_CREDENTIALS_JSON=GOOGLE_CREDENTIALS_JSON:latest'
  ]

# Build and push aika-backend-worker image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/aikaapp-584fa/aika-backend-worker', './backend-worker']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/aikaapp-584fa/aika-backend-worker']

# Deploy aika-backend-worker to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: [
    'run', 'deploy', 'aika-backend-worker',
    '--image', 'gcr.io/aikaapp-584fa/aika-backend-worker',
    '--region', 'asia-northeast1',
    '--platform', 'managed',
    '--allow-unauthenticated',
    '--timeout=600s',
    '--set-env-vars=VERTEX_AI_LOCATION=asia-northeast1',
    '--update-secrets=GOOGLE_PROJECT_ID=GOOGLE_PROJECT_ID:latest,GOOGLE_CREDENTIALS_JSON=GOOGLE_CREDENTIALS_JSON:latest,LINE_CHANNEL_ID=LINE_CHANNEL_ID:latest,LINE_CHANNEL_SECRET=LINE_CHANNEL_SECRET:latest,LINE_CHANNEL_ACCESS_TOKEN=LINE_CHANNEL_ACCESS_TOKEN:latest,FIREBASE_ADMIN_SDK_PRIVATE_KEY=FIREBASE_ADMIN_SDK_PRIVATE_KEY:latest,FIREBASE_STORAGE_BUCKET=FIREBASE_STORAGE_BUCKET:latest,FIREBASE_CLIENT_EMAIL=FIREBASE_CLIENT_EMAIL:latest,FIREBASE_PROJECT_ID=FIREBASE_PROJECT_ID:latest,VERTEXAI_API_KEY=VertexAIAPI:latest,IMAGEKIT_PRIVATE_KEY=IMAGEKIT_PRIVATE_KEY:latest,IMAGEKIT_PUBLIC_KEY=IMAGEKIT_PUBLIC_KEY:latest,IMAGEKIT_URL_ENDPOINT=IMAGEKIT_URL_ENDPOINT:latest,NEXT_PUBLIC_GOOGLE_SHEET_ID=NEXT_PUBLIC_GOOGLE_SHEET_ID:latest'
  ]

images:
- 'gcr.io/aikaapp-584fa/aika-backend'
- 'gcr.io/aikaapp-584fa/aika-backend-worker'