steps:
# 1. Dockerイメージをビルドします。シークレットをビルド引数として渡します。
- name: 'gcr.io/cloud-builders/docker'
  id: 'Build'
  secretEnv:
    - 'NEXT_PUBLIC_FIREBASE_API_KEY'
    - 'NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN'
    - 'NEXT_PUBLIC_FIREBASE_PROJECT_ID'
    - 'NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET'
    - 'NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID'
    - 'NEXT_PUBLIC_FIREBASE_APP_ID'
    - 'NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID'
  args: [
    'build',
    '--tag', 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/aika-app-repository/aika-app:$BUILD_ID',
    '--build-arg', 'NEXT_PUBLIC_FIREBASE_API_KEY=$$NEXT_PUBLIC_FIREBASE_API_KEY',
    '--build-arg', 'NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=$$NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN',
    '--build-arg', 'NEXT_PUBLIC_FIREBASE_PROJECT_ID=$$NEXT_PUBLIC_FIREBASE_PROJECT_ID',
    '--build-arg', 'NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=$$NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET',
    '--build-arg', 'NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=$$NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID',
    '--build-arg', 'NEXT_PUBLIC_FIREBASE_APP_ID=$$NEXT_PUBLIC_FIREBASE_APP_ID',
    '--build-arg', 'NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID=$$NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID',
    '.'
  ]

# 2. DockerイメージをArtifact Registryにプッシュします
- name: 'gcr.io/cloud-builders/docker'
  id: 'Push'
  args: [
    'push',
    'asia-northeast1-docker.pkg.dev/$PROJECT_ID/aika-app-repository/aika-app:$BUILD_ID'
  ]

# 3. Cloud Runにデプロイし、実行時シークレットをインジェクトします
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  id: 'Deploy'
  entrypoint: 'gcloud'
  args:
    - 'run'
    - 'deploy'
    - 'aika-app'
    - '--image'
    - 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/aika-app-repository/aika-app:$BUILD_ID'
    - '--region'
    - 'asia-northeast1'
    - '--platform'
    - 'managed'
    - '--allow-unauthenticated'
    - '--set-secrets=FIREBASE_ADMIN_SDK_PRIVATE_KEY=FIREBASE_ADMIN_SDK_PRIVATE_KEY:latest,NEXT_PUBLIC_FIREBASE_API_KEY=NEXT_PUBLIC_FIREBASE_API_KEY:latest,NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN:latest,NEXT_PUBLIC_FIREBASE_PROJECT_ID=NEXT_PUBLIC_FIREBASE_PROJECT_ID:latest,NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET:latest,NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID:latest,NEXT_PUBLIC_FIREBASE_APP_ID=NEXT_PUBLIC_FIREBASE_APP_ID:latest,NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID=NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID:latest'

# 作成したイメージを登録します
images:
- 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/aika-app-repository/aika-app:$BUILD_ID'

# ビルド時に利用可能なシークレットを定義します
availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/NEXT_PUBLIC_FIREBASE_API_KEY/versions/latest
    env: 'NEXT_PUBLIC_FIREBASE_API_KEY'
  - versionName: projects/$PROJECT_ID/secrets/NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN/versions/latest
    env: 'NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN'
  - versionName: projects/$PROJECT_ID/secrets/NEXT_PUBLIC_FIREBASE_PROJECT_ID/versions/latest
    env: 'NEXT_PUBLIC_FIREBASE_PROJECT_ID'
  - versionName: projects/$PROJECT_ID/secrets/NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET/versions/latest
    env: 'NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET'
  - versionName: projects/$PROJECT_ID/secrets/NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID/versions/latest
    env: 'NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID'
  - versionName: projects/$PROJECT_ID/secrets/NEXT_PUBLIC_FIREBASE_APP_ID/versions/latest
    env: 'NEXT_PUBLIC_FIREBASE_APP_ID'
  - versionName: projects/$PROJECT_ID/secrets/NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID/versions/latest
    env: 'NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID'

# ビルドのオプション設定
options:
  logging: CLOUD_LOGGING_ONLY
