# filename: cloudbuild.yaml
# 目的: ビルドが確実に通るかの最小構成で検証する
steps:
  # 1) Node イメージで依存をインストール
  - name: node:20-alpine
    entrypoint: sh
    args:
      - -c
      - |
        corepack enable
        npm ci
        npm run build
        # 必要に応じて test も: npm test

# 成果物を Cloud Storage 等に出さない最小構成
options:
  logging: CLOUD_LOGGING_ONLY

# ビルドキャッシュを有効化（同一イメージ再利用時）
# Cloud Build のキャッシュは docker builder 使用時のみ強いですが、ここでは最小構成のため省略
timeout: "1200s"
