steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/aikaapp:latest', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/aikaapp:latest']
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'gcloud'
  args:
    - 'run'
    - 'deploy'
    - 'aikaapp'
    - '--image=gcr.io/$PROJECT_ID/aikaapp:latest'
    - '--region=europe-west1'
    - '--platform=managed'
    - '--allow-unauthenticated'
images:
- 'gcr.io/$PROJECT_ID/aikaapp:latest'
options:
  logging: CLOUD_LOGGING_ONLY