steps:
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '-t'
  - 'gcr.io/innate-algebra-474710-f0/aikaapp-main:$COMMIT_SHA'
  - '.'
images:
- 'gcr.io/innate-algebra-474710-f0/aikaapp-main:$COMMIT_SHA'
options:
  logging: CLOUD_LOGGING_ONLY