steps:
  - name: gcr.io/cloud-builders/docker
    args:
      [
        'build',
        '-t',
        'gcr.io/$PROJECT_ID/aika-backend:latest',
        './backend'
      ]
images:
  - gcr.io/$PROJECT_ID/aika-backend:latest