steps:
# ==============================================================================
# ステップ1: Dockerイメージのビルド
# ==============================================================================
- name: 'gcr.io/cloud-builders/docker'
  id: 'Build Image'
  args:
    - 'build'
    - '--build-arg'
    - 'GOOGLE_CREDENTIALS_JSON=$$GOOGLE_CREDENTIALS_JSON'
    - '--build-arg'
    - 'IMAGEKIT_PRIVATE_KEY=$$IMAGEKIT_PRIVATE_KEY'
    - '--build-arg'
    - 'LINE_CHANNEL_ID=$$LINE_CHANNEL_ID'
    - '--build-arg'
    - 'LINE_CHANNEL_SECRET=$$LINE_CHANNEL_SECRET'
    - '--build-arg'
    - 'NEXT_PUBLIC_GOOGLE_SHEET_ID=$$NEXT_PUBLIC_GOOGLE_SHEET_ID'
    - '--build-arg'
    - 'NEXT_PUBLIC_IMAGEKIT_PUBLIC_KEY=$$NEXT_PUBLIC_IMAGEKIT_PUBLIC_KEY'
    - '--build-arg'
    - 'NEXT_PUBLIC_IMAGEKIT_URL_ENDPOINT=$$NEXT_PUBLIC_IMAGEKIT_URL_ENDPOINT'
    - '--build-arg'
    - 'VertexAIAPI=$$VertexAIAPI'
    - '--build-arg'
    - 'STORAGE_BUCKET=$$STORAGE_BUCKET_VALUE'
    - '-t'
    - 'gcr.io/innate-algebra-474710-f0/aikaapp:latest'
    - '.'
  secretEnv:
    - 'GOOGLE_CREDENTIALS_JSON'
    - 'IMAGEKIT_PRIVATE_KEY'
    - 'LINE_CHANNEL_ID'
    - 'LINE_CHANNEL_SECRET'
    - 'NEXT_PUBLIC_GOOGLE_SHEET_ID'
    - 'NEXT_PUBLIC_IMAGEKIT_PUBLIC_KEY'
    - 'NEXT_PUBLIC_IMAGEKIT_URL_ENDPOINT'
    - 'VertexAIAPI'
    - 'STORAGE_BUCKET_VALUE'

# ==============================================================================
# ステップ2: ビルドされたDockerイメージをContainer Registryにプッシュ
# ==============================================================================
- name: 'gcr.io/cloud-builders/docker'
  id: 'Push Image'
  args: ['push', 'gcr.io/innate-algebra-474710-f0/aikaapp:latest']
  waitFor: ['Build Image']

# ==============================================================================
# ステップ3: DockerイメージをCloud Runにデプロイ
# ==============================================================================
- name: 'gcr.io/cloud-builders/gcloud'
  id: 'Deploy to Cloud Run'
  args:
    - 'run'
    - 'deploy'
    - 'aikaapp'
    - '--image'
    - 'gcr.io/innate-algebra-474710-f0/aikaapp:latest'
    - '--region'
    - 'asia-northeast1'
    - '--platform'
    - 'managed'
    - '--allow-unauthenticated'
    - '--memory'
    - '512Mi'
    - '--cpu'
    - '1'
    - '--set-secrets'
    - 'GOOGLE_CREDENTIALS_JSON=GOOGLE_CREDENTIALS_JSON:latest'
    - '--set-secrets'
    - 'IMAGEKIT_PRIVATE_KEY=IMAGEKIT_PRIVATE_KEY:latest'
    - '--set-secrets'
    - 'LINE_CHANNEL_ID=LINE_CHANNEL_ID:latest'
    - '--set-secrets'
    - 'LINE_CHANNEL_SECRET=LINE_CHANNEL_SECRET:latest'
    - '--set-secrets'
    - 'NEXT_PUBLIC_GOOGLE_SHEET_ID=NEXT_PUBLIC_GOOGLE_SHEET_ID:latest'
    - '--set-secrets'
    - 'NEXT_PUBLIC_IMAGEKIT_PUBLIC_KEY=NEXT_PUBLIC_IMAGEKIT_PUBLIC_KEY:latest'
    - '--set-secrets'
    - 'NEXT_PUBLIC_IMAGEKIT_URL_ENDPOINT=NEXT_PUBLIC_IMAGEKIT_URL_ENDPOINT:latest'
    - '--set-secrets'
    - 'VertexAIAPI=VertexAIAPI:latest'
    - '--set-secrets'
    - 'STORAGE_BUCKET=FIREBASE_STORAGE_BUCKET_SECRET:latest'
  waitFor: ['Push Image']

availableSecrets:
  secretManager:
  - versionName: projects/innate-algebra-474710-f0/secrets/GOOGLE_CREDENTIALS_JSON/versions/latest
    env: 'GOOGLE_CREDENTIALS_JSON'
  - versionName: projects/innate-algebra-474710-f0/secrets/IMAGEKIT_PRIVATE_KEY/versions/latest
    env: 'IMAGEKIT_PRIVATE_KEY'
  - versionName: projects/innate-algebra-474710-f0/secrets/LINE_CHANNEL_ID/versions/latest
    env: 'LINE_CHANNEL_ID'
  - versionName: projects/innate-algebra-474710-f0/secrets/LINE_CHANNEL_SECRET/versions/latest
    env: 'LINE_CHANNEL_SECRET'
  - versionName: projects/innate-algebra-474710-f0/secrets/NEXT_PUBLIC_GOOGLE_SHEET_ID/versions/latest
    env: 'NEXT_PUBLIC_GOOGLE_SHEET_ID'
  - versionName: projects/innate-algebra-474710-f0/secrets/NEXT_PUBLIC_IMAGEKIT_PUBLIC_KEY/versions/latest
    env: 'NEXT_PUBLIC_IMAGEKIT_PUBLIC_KEY'
  - versionName: projects/innate-algebra-474710-f0/secrets/NEXT_PUBLIC_IMAGEKIT_URL_ENDPOINT/versions/latest
    env: 'NEXT_PUBLIC_IMAGEKIT_URL_ENDPOINT'
  - versionName: projects/innate-algebra-474710-f0/secrets/VertexAIAPI/versions/latest
    env: 'VertexAIAPI'
  - versionName: projects/aika-202510/secrets/FIREBASE_STORAGE_BUCKET_SECRET/versions/latest
    env: 'STORAGE_BUCKET_VALUE'

options:
  logging: CLOUD_LOGGING_ONLY
