steps:
  # Build the main backend service
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-backend'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/aika-backend:latest', './backend']

  # Build the backend worker service
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-worker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/aika-backend-worker:latest', './backend-worker']

  # Deploy main backend to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'aika-backend' # Service name
      - '--image'
      - 'gcr.io/$PROJECT_ID/aika-backend:latest'
      - '--region'
      - 'asia-northeast1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
    waitFor: ['build-backend'] # Wait for the image to be built

  # Deploy backend worker to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'aika-backend-worker' # Service name
      - '--image'
      - 'gcr.io/$PROJECT_ID/aika-backend-worker:latest'
      - '--region'
      - 'asia-northeast1'
      - '--platform'
      - 'managed'
      - '--no-allow-unauthenticated' # Worker should not be public
    waitFor: ['build-worker'] # Wait for the image to be built

# Push all built images to Google Container Registry
images:
  - 'gcr.io/$PROJECT_ID/aika-backend:latest'
  - 'gcr.io/$PROJECT_ID/aika-backend-worker:latest'

options:
  logging: CLOUD_LOGGING_ONLY